[CONDITIONS]
condition01 = resting
condition02 = FGF1
condition03 = FGF4
condition04 = FGF8b
condition05 = FGF9

[DIRECTORIES]
# directory to extracted data -> one directory per day
dir01 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-04-30_CHO_FGFR1cHT7_SiRHTL---\analysis\data_extraction
dir02 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-09-24_CHO_FGFR1cHT7_SiRHTL---\analysis\data_extraction
dir03 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-10-01_CHO_FGFR1cHT7_SiRHTL---\analysis\data_extraction
dir04 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-10-31_CHO_FGFR1cHT7-SiRHTL---\analysis\data_extraction

[ANALYSIS]
diffusion_coefficient_global = false
diffusion_coefficient_free = false
diffusion_modes = true
segment_lengths_global = false
segment_lengths_free = false
segment_number_global = false

[STATISTICS]
run_statistics = false
p_value = 0.5
significant = 0.05
highly_significant = 0.01
very_highly_significant = 0.001

[SAVE_DIRECTORY]
save_dir = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\pooled_analysis