# creates means over bins of data by cell number or time, plots them, and runs statistical tests on them
[GLOBAL_DIR]
# define the directories to the .h5 files. They MUST have their associated date before the first underscore and the coverslip name before the second to last.
# They must have been created by filtering for every parameter (global)
dir = C:\Users\pcoffice22\Documents\Meine_Dokumente\test\2025-04-30_CHO_FGFR1cHT7_SiRHTL_test\analysis\FGF1\250503_filtered

[CS_DIRS]
# directories of the analyzed coverslips
dir01 = C:\Users\pcoffice22\Documents\Meine_Dokumente\test\2025-04-30_CHO_FGFR1cHT7_SiRHTL_test\CS2
dir02 = C:\Users\pcoffice22\Documents\Meine_Dokumente\test\2025-04-30_CHO_FGFR1cHT7_SiRHTL_test\CS7

[LIGAND_ADDITION]
ligand_time = txt

[BINNING]
# whether or not to use timestamps instead of cell numbers for binning; the cell to which a ligand was added first (leave empty if you use timestamps)
# size of the bins over which to calculate means. in cells if use_timestamps = false, in minutes if use_timestamps = true
use_timestamps = true
bin_size = 10

[PLOT_SETTINGS]
# dot_color: color for plots in hexcode; ligand_index: time before ligand was added (leave empty if no ligand was used),
# unit cells if use_timestamps is false, unit seconds if true; ligand_name: name of the ligand; error_type: error type for error bars (SD or SEM)
dot_color = #E69F00
ligand = true
ligand_index = 6
ligand_name= FGF1
error_type = SEM

[STAT_SETTINGS]
# interval values for the statistical tests, run_stats: true to run statistical tests;
# alpha: p value; alpha_sign_1, alpha_sign_2, alpha_sign_3: significance levels from 1 lowest significance to 3 highest significance
run_stats = true
alpha_norm = 0.05
alpha_sign_1 = 0.05
alpha_sign_2 = 0.01
alpha_sign_3 = 0.001

[SAVE_DIR]
# where to create the time-resolved analysis folder
save_dir = C:\Users\pcoffice22\Documents\Meine_Dokumente\test\2025-04-30_CHO_FGFR1cHT7_SiRHTL_test\time_resolved_analysis_tests