# creates means over bins of data by cell number or time, plots them, and runs statistical tests on them
[GLOBAL_DIR]
# define the directories to the .h5 files. They MUST have their associated date before the first underscore and the coverslip name before the second to last.
# They must have been created by filtering for every parameter (global)
dir01 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-04-30_CHO_FGFR1cHT7_SiRHTL---\analysis\FGF1\250503_filtered
dir02 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-09-24_CHO_FGFR1cHT7_SiRHTL---\analysis\FGF1\251001_filtered
dir03 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-10-01_CHO_FGFR1cHT7_SiRHTL---\analysis\FGF1\251005_filtered
dir04 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-10-31_CHO_FGFR1cHT7-SiRHTL---\analysis\FGF1\251103_filtered

[CS_DIRS]
# directories of the analyzed coverslips
dir01 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-04-30_CHO_FGFR1cHT7_SiRHTL---\CS2
dir02 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-04-30_CHO_FGFR1cHT7_SiRHTL---\CS7
dir03 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-09-24_CHO_FGFR1cHT7_SiRHTL---\CS2
dir04 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-09-24_CHO_FGFR1cHT7_SiRHTL---\CS7
dir05 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-10-01_CHO_FGFR1cHT7_SiRHTL---\CS2
dir06 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-10-01_CHO_FGFR1cHT7_SiRHTL---\CS7
dir07 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-10-31_CHO_FGFR1cHT7-SiRHTL---\CS2
dir08 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\2025-10-31_CHO_FGFR1cHT7-SiRHTL---\CS7

[LIGAND_ADDITION]
ligand_time = txt

[BINNING]
# whether or not to use timestamps instead of cell numbers for binning; the cell to which a ligand was added first (leave empty if you use timestamps)
# size of the bins over which to calculate means. in cells if use_timestamps = false, in minutes if use_timestamps = true
use_timestamps = true
bin_size = 5

[PLOT_SETTINGS]
# dot_color: color for plots in hexcode; ligand_index: time before ligand was added (leave empty if no ligand was used),
# unit cells if use_timestamps is false, unit seconds if true; ligand_name: name of the ligand; error_type: error type for error bars (SD or SEM)
ligand_exists = true
ligand_name = FGF1
resting_shift = -10
x_start_time = -10
x_end_time = 40
y_start_diffusion = 0.08
y_end_diffusion = 0.22
y_start_immobile = 20
y_end_immobile = 55

dot_color = #E69F00
error_type = SEM

[STAT_SETTINGS]
# interval values for the statistical tests, run_stats: true to run statistical tests;
# alpha: p value; alpha_sign_1, alpha_sign_2, alpha_sign_3: significance levels from 1 lowest significance to 3 highest significance
run_stats = true
alpha_norm = 0.05
alpha_sign_1 = 0.05
alpha_sign_2 = 0.01
alpha_sign_3 = 0.001

[SAVE_DIR]
# where to create the time-resolved analysis folder
save_dir = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis