[DIRS]
dir01 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_FGF1\binned_data_FGF1_6.41min.csv
dir02 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_FGF4\binned_data_FGF4_7.33min.csv
dir03 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_FGF8b\binned_data_FGF8b_6.64min.csv
dir04 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_FGF9\binned_data_FGF9_7.19min.csv
dir05 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_resting\binned_data_resting_6.24min.csv
#dir01 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_FGF1\binned_data_FGF1_5min.csv
#dir02 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_FGF4\binned_data_FGF4_5min.csv
#dir03 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_FGF8b\binned_data_FGF8b_5min.csv
#dir04 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_FGF9\binned_data_FGF9_5min.csv
#dir05 = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis\time_resolved_analysis_resting\binned_data_resting_5min.csv

[PLOT_SETTINGS]
x_start_time = -12
x_end_time = 33
y_start_diffusion = 0.10
y_end_diffusion = 0.20
y_start_immobile =
y_end_immobile =

[SAVE_DIR]
save_dir = C:\Users\pcoffice22\Documents\Meine_Dokumente\02_Research\01_biased_activation_of_FGFR\SPT_NSTORM\time_resolved_analysis